/* Magic Bitboard Data
 * This file was generated by magic_bitboard_generator.
 */

#ifndef CHESS_CORE_MAGIC_BITBOARD_DATA_H
#define CHESS_CORE_MAGIC_BITBOARD_DATA_H

#include "chess_core/magic.h"

namespace chess_core {

inline constexpr MagicDataSet magic_rook_data{
    MagicData{.magic_number = 0x018004c001132084, .max_index = 4095, .shift = 52}, MagicData{.magic_number = 0x8020001000080020, .max_index = 2047, .shift = 52},
    MagicData{.magic_number = 0x0820100804040820, .max_index = 2046, .shift = 53}, MagicData{.magic_number = 0x0040080040040002, .max_index = 2047, .shift = 52},
    MagicData{.magic_number = 0x0040040040020001, .max_index = 2047, .shift = 52}, MagicData{.magic_number = 0x020002001041280c, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x0040008001000040, .max_index = 2047, .shift = 52}, MagicData{.magic_number = 0x0200022100804402, .max_index = 4095, .shift = 52},
    MagicData{.magic_number = 0x4040800080400023, .max_index = 2047, .shift = 53}, MagicData{.magic_number = 0x3000100400080011, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0000404010000800, .max_index = 1023, .shift = 53}, MagicData{.magic_number = 0x0016000a2046004a, .max_index = 1022, .shift = 54},
    MagicData{.magic_number = 0x0080200200010020, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x4000200100008020, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0000400080004001, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x00410000a1001042, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x0440002000100020, .max_index = 2047, .shift = 52}, MagicData{.magic_number = 0x9410000802040008, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0004000801020008, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0004002020020004, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0002001010010080, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x00d1001010008040, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x4080004040008001, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0010420004084081, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x0000410100208000, .max_index = 2047, .shift = 53}, MagicData{.magic_number = 0x0c00080010040010, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0004020008010008, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0400040020020020, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0400020020010020, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0000008020200100, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0020400040008001, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0210604200048104, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x0840001000200020, .max_index = 2047, .shift = 52}, MagicData{.magic_number = 0x0900080400100010, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0004020100080008, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0000200400200200, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0802001080100100, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x0420200100200080, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0140008000404001, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x4800018312001644, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x1803804010218000, .max_index = 2047, .shift = 53}, MagicData{.magic_number = 0x1000802000408014, .max_index = 1023, .shift = 53},
    MagicData{.magic_number = 0x0000080010004040, .max_index = 1023, .shift = 53}, MagicData{.magic_number = 0x0000020004002020, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0100020001002020, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x8401002000802001, .max_index = 1023, .shift = 52},
    MagicData{.magic_number = 0x0000004000802020, .max_index = 1023, .shift = 52}, MagicData{.magic_number = 0x4080208910520004, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x48fffe99fecfaa00, .max_index = 1023, .shift = 54}, MagicData{.magic_number = 0x48fffe99fecfaa00, .max_index = 511, .shift = 55},
    MagicData{.magic_number = 0x497fffadff9c2e00, .max_index = 511, .shift = 55},  MagicData{.magic_number = 0x613fffddffce9200, .max_index = 511, .shift = 55},
    MagicData{.magic_number = 0xffffffe9ffe7ce00, .max_index = 511, .shift = 55},  MagicData{.magic_number = 0xfffffff5fff3e600, .max_index = 511, .shift = 55},
    MagicData{.magic_number = 0x0003ff95e5e6a4c0, .max_index = 511, .shift = 55},  MagicData{.magic_number = 0x510ffff5f63c96a0, .max_index = 1023, .shift = 54},
    MagicData{.magic_number = 0xebffffb9ff9fc526, .max_index = 2047, .shift = 53}, MagicData{.magic_number = 0x61fffeddfeedaeae, .max_index = 1023, .shift = 54},
    MagicData{.magic_number = 0x53bfffedffdeb1a2, .max_index = 1023, .shift = 54}, MagicData{.magic_number = 0x127fffb9ffdfb5f6, .max_index = 1023, .shift = 54},
    MagicData{.magic_number = 0x411fffddffdbf4d6, .max_index = 1023, .shift = 54}, MagicData{.magic_number = 0x0002001003880402, .max_index = 2047, .shift = 53},
    MagicData{.magic_number = 0x0003ffef27eebe74, .max_index = 1023, .shift = 54}, MagicData{.magic_number = 0x7645fffecbfea79e, .max_index = 2047, .shift = 53},
};

inline constexpr MagicDataSet magic_bishop_data{
    MagicData{.magic_number = 0x002111a0c1004082, .max_index = 49, .shift = 58},  MagicData{.magic_number = 0x001109c0c0808400, .max_index = 25, .shift = 59},
    MagicData{.magic_number = 0x01418300a0600020, .max_index = 29, .shift = 59},  MagicData{.magic_number = 0x4022aa0164808000, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x0208441008000000, .max_index = 31, .shift = 58},  MagicData{.magic_number = 0x0000e14509007845, .max_index = 29, .shift = 58},
    MagicData{.magic_number = 0x00213220c4040b21, .max_index = 25, .shift = 58},  MagicData{.magic_number = 0x601c2a0132604202, .max_index = 61, .shift = 58},
    MagicData{.magic_number = 0x0266130880e10041, .max_index = 25, .shift = 58},  MagicData{.magic_number = 0x0002134881007080, .max_index = 25, .shift = 59},
    MagicData{.magic_number = 0x0002458240604008, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x000822aa01640201, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x0100010108001001, .max_index = 31, .shift = 58},  MagicData{.magic_number = 0x800801c289940402, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x0110011261018800, .max_index = 25, .shift = 58},  MagicData{.magic_number = 0x00200c1981814308, .max_index = 25, .shift = 58},
    MagicData{.magic_number = 0x00202103028300c2, .max_index = 29, .shift = 58},  MagicData{.magic_number = 0x0004020060602830, .max_index = 29, .shift = 56},
    MagicData{.magic_number = 0x0400080010101010, .max_index = 127, .shift = 52}, MagicData{.magic_number = 0x0800084080200440, .max_index = 127, .shift = 53},
    MagicData{.magic_number = 0x0000800840808024, .max_index = 129, .shift = 56}, MagicData{.magic_number = 0x0000042040420040, .max_index = 127, .shift = 54},
    MagicData{.magic_number = 0x0822020030a30308, .max_index = 29, .shift = 58},  MagicData{.magic_number = 0x40420004b1310180, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x0820200005699545, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x000820000d0281a0, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x0000801000204010, .max_index = 127, .shift = 53}, MagicData{.magic_number = 0x0200400401001004, .max_index = 511, .shift = 52},
    MagicData{.magic_number = 0x0000200800808010, .max_index = 511, .shift = 53}, MagicData{.magic_number = 0x0f80100400404200, .max_index = 127, .shift = 54},
    MagicData{.magic_number = 0x0404040204526551, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x00c300a02052c554, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x0002863a00212000, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x0601430d03103000, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x0010108020001040, .max_index = 127, .shift = 53}, MagicData{.magic_number = 0x0000004010010010, .max_index = 511, .shift = 52},
    MagicData{.magic_number = 0x0200802002008008, .max_index = 511, .shift = 52}, MagicData{.magic_number = 0x4400408002002008, .max_index = 127, .shift = 53},
    MagicData{.magic_number = 0x04030149a0060808, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x0002c1282c020200, .max_index = 30, .shift = 59},
    MagicData{.magic_number = 0x580265428a144000, .max_index = 29, .shift = 59},  MagicData{.magic_number = 0xa100a30303102001, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x0000082080100020, .max_index = 127, .shift = 53}, MagicData{.magic_number = 0x0000008080801040, .max_index = 128, .shift = 56},
    MagicData{.magic_number = 0x0088010020090080, .max_index = 127, .shift = 54}, MagicData{.magic_number = 0x0202004040020001, .max_index = 127, .shift = 52},
    MagicData{.magic_number = 0x00060140c0310a00, .max_index = 29, .shift = 58},  MagicData{.magic_number = 0xc0060140c0304603, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x010282650484ea00, .max_index = 23, .shift = 59},  MagicData{.magic_number = 0x902099450242c004, .max_index = 23, .shift = 59},
    MagicData{.magic_number = 0x8020206181418104, .max_index = 29, .shift = 59},  MagicData{.magic_number = 0x4482020008404000, .max_index = 31, .shift = 56},
    MagicData{.magic_number = 0x0022420100202000, .max_index = 31, .shift = 55},  MagicData{.magic_number = 0x010010072ba44000, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x4408032404ca2024, .max_index = 25, .shift = 59},  MagicData{.magic_number = 0xa00a04c510604882, .max_index = 23, .shift = 59},
    MagicData{.magic_number = 0x0042005191b00300, .max_index = 61, .shift = 58},  MagicData{.magic_number = 0x0020408080c9910c, .max_index = 25, .shift = 59},
    MagicData{.magic_number = 0x04800d304062c496, .max_index = 30, .shift = 59},  MagicData{.magic_number = 0x0180040400084040, .max_index = 31, .shift = 56},
    MagicData{.magic_number = 0x0400000401002020, .max_index = 31, .shift = 55},  MagicData{.magic_number = 0x000014120a0281c4, .max_index = 29, .shift = 59},
    MagicData{.magic_number = 0x0080131405014050, .max_index = 23, .shift = 59},  MagicData{.magic_number = 0x0000810040800401, .max_index = 63, .shift = 54},
};

} // namespace chess_core

#endif
